# use version 2.0
version: 2

jobs:
  "test": &test
    # run the step
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/tingShean/projectRL
    steps: &steps
      - checkout
      - run: go version
      - run:
          name: "Fetch dependecies"
          command: >
            go get -t -v ./...
      - run: go test -v -race ./...

  "latest"
    <<: *test
    enviroment:
      LATEST: true

  "1.13":
    <<: *test
    docker:
      - image: circleci/golang:1.13

  "1.12":
    <<: *test
    docker:
      - image: circleci/golang:1.12
