# use version 2.0
version: 2

jobs:
  "test": &test
    # run the step
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/tingShean/projectRL
    steps: &steps
      - checkout
      - run: go version
      - run:
          name: "Fetch dependecies"
          command: >
            go get -t -v ./...
      - run: go test -v -race ./...

  build:
    environame:
      IMAGE_NAME: jonathancardoso/building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .

  "latest":
    <<: *test
    enviroment:
      LATEST: true

  "1.12":
    <<: *test
    docker:
      - image: circleci/golang:1.12

workflows:
  version: 2
  build:
    jobs:
      - "latest"
      - "1.12"
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
