# use version 2.0
version: 2

jobs:
  "test": &test
    # run the step
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/tingShean/projectRL
    steps: &steps
      - checkout
      - run: go version
      - run:
          name: "Fetch dependecies"
          command: >
            go get -t -v ./...
      - run: go test -v -race ./...

  "latest":
    <<: *test
    enviroment:
      LATEST: true

  "1.12":
    <<: *test
    docker:
      - image: circleci/golang:1.12

  "1.11":
    <<: *test
    docker:
      - image: circleci/golang:1.11

  "1.10":
    <<: *test
    docker:
      - image: circleci/golang:1.10

workflows:
  version: 2
  build:
    jobs:
      - "latest"
      - "1.12"
      - "1.11"
      - "1.10"
